// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDFT1m6Wsbcm3KgcptxXCCbMoFf9SfoTRs',
      appId: '1:703890941070:android:023e758e718816aed795df',
      messagingSenderId: '703890941070',
      projectId: 'bioveg-ca9ae',
      storageBucket: 'bioveg-ca9ae.appspot.com',
      databaseURL:
          'https://bioveg-ca9ae-default-rtdb.europe-west1.firebasedatabase.app');

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyAn62nZtVLW2X-PEpGhNPF50x3gbXy5HQI',
      appId: '1:703890941070:ios:cad14601aabdd10ed795df',
      messagingSenderId: '703890941070',
      projectId: 'bioveg-ca9ae',
      storageBucket: 'bioveg-ca9ae.appspot.com',
      iosClientId:
          '703890941070-pnfpj6n6o1ppqefdob3u7n1j2p4k30vh.apps.googleusercontent.com',
      iosBundleId: 'com.example.bioVeg',
      databaseURL:
          'https://bioveg-ca9ae-default-rtdb.europe-west1.firebasedatabase.app');
}
